import { NextRequest, NextResponse } from "next/server";
import { agentSupabase } from "@/lib/agent-supabase";
import { generateAgentWallet, getAgentWalletClient, getSepoliaPublicClient, decryptPrivateKey } from "@/lib/agent-wallet";
import { CONTRACT_ADDRESSES, DELEGATE_REGISTRY_ABI } from "@/constants/contracts";

export async function GET(req: NextRequest) {
  const agentId = req.nextUrl.searchParams.get("agentId");
  const owner = req.nextUrl.searchParams.get("owner");

  if (!agentId && !owner) {
    return NextResponse.json({ error: "agentId or owner is required" }, { status: 400 });
  }

  let query = agentSupabase
    .from("agents")
    .select("agent_id, owner, telegram_bot_token, telegram_chat_id, agent_wallet_address, created_at");

  if (agentId) {
    query = query.eq("agent_id", Number(agentId));
  } else if (owner) {
    query = query.eq("owner", owner.toLowerCase());
  }

  const { data, error } = await query.single();

  if (error || !data) {
    return NextResponse.json({ telegramConnected: false });
  }

  return NextResponse.json({
    id: data.agent_id,
    owner: data.owner,
    telegramTokenSaved: !!data.telegram_bot_token,
    telegramConnected: !!data.telegram_bot_token && !!data.telegram_chat_id,
    agentWalletAddress: data.agent_wallet_address || null,
    createdAt: data.created_at,
  });
}

export async function POST(req: NextRequest) {
  try {
    const { owner, chainId } = await req.json();

    if (!owner) {
      return NextResponse.json(
        { error: "owner is required" },
        { status: 400 }
      );
    }

    const normalizedOwner = owner.toLowerCase();
    const chain = chainId ?? 11155111;

    // Check if agent already exists for this owner + chain
    const { data: existing } = await agentSupabase
      .from("agents")
      .select("agent_id, agent_wallet_address, created_at")
      .eq("owner", normalizedOwner)
      .eq("chain_id", chain)
      .single();

    if (existing) {
      return NextResponse.json({
        success: true,
        id: existing.agent_id,
        agentWalletAddress: existing.agent_wallet_address || null,
        createdAt: existing.created_at,
        existing: true,
      });
    }

    // Generate agent wallet
    let walletFields: { agent_wallet_address?: string; encrypted_private_key?: string } = {};
    try {
      const wallet = generateAgentWallet();
      walletFields = {
        agent_wallet_address: wallet.address,
        encrypted_private_key: wallet.encryptedPrivateKey,
      };

      // Auto-register agent as delegate on-chain
      try {
        const { getRelayerWalletClient } = await import("@/lib/agent-wallet");
        const relayerClient = getRelayerWalletClient();
        const publicClient = getSepoliaPublicClient();

        // Send 0.0005 ETH to agent for registerDelegate gas
        const fundTx = await relayerClient.sendTransaction({
          to: wallet.address as `0x${string}`,
          value: 500_000_000_000_000n, // 0.0005 ETH
        });
        await publicClient.waitForTransactionReceipt({ hash: fundTx, timeout: 60_000 });

        // Agent registers itself as delegate
        const privateKey = decryptPrivateKey(wallet.encryptedPrivateKey);
        const agentClient = getAgentWalletClient(privateKey);
        const addresses = CONTRACT_ADDRESSES[11155111];

        const regTx = await agentClient.writeContract({
          address: addresses.delegateRegistry as `0x${string}`,
          abi: DELEGATE_REGISTRY_ABI,
          functionName: "registerDelegate",
          args: ["DAO Agent", "Automated voting agent", "governance"],
        });
        await publicClient.waitForTransactionReceipt({ hash: regTx, timeout: 60_000 });

        console.log("Agent registered as delegate:", wallet.address);
      } catch (regErr) {
        console.warn("Agent delegate registration failed:", regErr);
      }
    } catch {
      console.warn("Agent wallet generation skipped: AGENT_ENCRYPTION_KEY not set");
    }

    // Insert new agent (agent_id auto-generated by Supabase)
    const { data: inserted, error } = await agentSupabase
      .from("agents")
      .insert({
        chain_id: chain,
        owner: normalizedOwner,
        ...walletFields,
      })
      .select("agent_id, created_at")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      id: inserted.agent_id,
      agentWalletAddress: walletFields.agent_wallet_address || null,
      createdAt: inserted.created_at,
      existing: false,
    });
  } catch {
    return NextResponse.json(
      { error: "Invalid request" },
      { status: 400 }
    );
  }
}

export async function PATCH(req: NextRequest) {
  try {
    const { agentId, owner, telegramBotToken } = await req.json();

    if (!agentId) {
      return NextResponse.json(
        { error: "agentId is required" },
        { status: 400 }
      );
    }

    const { error } = await agentSupabase
      .from("agents")
      .update({
        telegram_bot_token: telegramBotToken || null,
      })
      .eq("agent_id", Number(agentId));

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json(
      { error: "Invalid request" },
      { status: 400 }
    );
  }
}
