"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { useAccount, useChainId, usePublicClient } from "wagmi";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input, Textarea, Label, HelperText } from "@/components/ui/input";
import { cn, formatVTON } from "@/lib/utils";
import { usePropose, useGovernanceParams } from "@/hooks/contracts/useDAOGovernor";
import { useTONAllowance, useApproveTON, useTONBalance, useClaimTON } from "@/hooks/contracts/useTON";
import { useVTONBalance, useTotalSupply } from "@/hooks/contracts/useVTON";
import { useClaimFromFaucet, useFaucetConfig } from "@/hooks/contracts/useVTONFaucet";
import { useTotalDelegated } from "@/hooks/contracts/useDelegateRegistry";
import { getContractAddresses, DAO_GOVERNOR_ABI } from "@/constants/contracts";
import { parseEventLogs } from "viem";
import { ActionBuilderList, DEFAULT_ACTION } from "./ActionBuilderList";
import type { BuiltAction } from "./ActionBuilder";
import { useCompanion } from "@/components/companion/CompanionProvider";
import { normalizeArgs, type ExtractedProposal, type ProposalCalldata } from "@/lib/companion/proposal-data";

/** Read-only display for agent-generated actions */
function AgentActionList({
  data,
  onClear,
}: {
  data: ProposalCalldata;
  onClear: () => void;
}) {
  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <p className="text-xs font-medium text-[var(--text-brand)]">
          Generated by AI Companion
        </p>
        <Button type="button" variant="ghost" size="xs" onClick={onClear}>
          Clear &amp; Edit Manually
        </Button>
      </div>
      {data.decodedCalls.map((call, i) => (
        <div
          key={i}
          className="p-3 rounded-lg border border-[var(--border-default)] space-y-2"
        >
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-[var(--text-primary)]">
              Action {i + 1}
            </span>
            <span className="text-xs text-[var(--text-tertiary)]">
              {call.targetName}
            </span>
          </div>
          <div className="space-y-1 text-xs">
            <p className="text-[var(--text-secondary)]">
              <span className="text-[var(--text-tertiary)]">Function: </span>
              {call.functionName}
            </p>
            <p className="text-[var(--text-secondary)] font-mono truncate">
              <span className="text-[var(--text-tertiary)] font-sans">Target: </span>
              {call.target}
            </p>
            {call.args.length > 0 && (
              <div className="pl-2 border-l-2 border-[var(--border-primary)] space-y-0.5 mt-1">
                {normalizeArgs(call.args).map((arg, j) => (
                  <p key={j} className="text-[var(--text-secondary)]">
                    <span className="text-[var(--text-tertiary)]">{arg.name}: </span>
                    <span className="font-mono">{arg.value}</span>
                  </p>
                ))}
              </div>
            )}
            <div className="mt-1">
              <p className="text-[var(--text-tertiary)]">Calldata:</p>
              <p className="font-mono text-[var(--text-secondary)] break-all bg-[var(--bg-tertiary)] rounded p-1.5 mt-0.5">
                {data.functionBytecodes[i] || call.calldata}
              </p>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

export interface CreateProposalFormProps {
  className?: string;
}

export function CreateProposalForm({ className }: CreateProposalFormProps) {
  const router = useRouter();
  const { address, isConnected } = useAccount();
  const chainId = useChainId();
  const publicClient = usePublicClient();
  const addresses = getContractAddresses(chainId);

  const [title, setTitle] = React.useState("");
  const [description, setDescription] = React.useState("");
  const [burnRateInput, setBurnRateInput] = React.useState<string>("");
  const [showAdvanced, setShowAdvanced] = React.useState(false);
  const [actions, setActions] = React.useState<BuiltAction[]>([
    { ...DEFAULT_ACTION },
  ]);
  const [agentProposal, setAgentProposal] = React.useState<ExtractedProposal | null>(null);

  const { registerApplyProposal } = useCompanion();

  const { proposeAsync } = usePropose();
  const { proposalCreationCost, proposalThreshold, isLoading: isGovernanceLoading } = useGovernanceParams();

  // vTON balance and threshold state
  const { data: vtonBalance, refetch: refetchVTONBalance } = useVTONBalance(address);
  const { data: vtonTotalSupply, isLoading: isTotalSupplyLoading } = useTotalSupply();
  const { data: delegatedToMe } = useTotalDelegated(address);

  // Loading state for vTON requirements
  // Also treat undefined data as loading (data may be undefined even after isLoading becomes false)
  const isVTONDataLoading = isGovernanceLoading || isTotalSupplyLoading ||
    vtonTotalSupply === undefined || proposalThreshold === undefined;


  // Total voting power = balance + delegated to me
  const totalVotingPower = (vtonBalance ?? BigInt(0)) + (delegatedToMe ?? BigInt(0));

  // TON Faucet
  const {
    claim: claimTON,
    isPending: isTONClaimPending,
    isConfirming: isTONClaimConfirming,
    isConfirmed: isTONClaimConfirmed,
    reset: resetTONClaim,
    claimAmount: tonClaimAmount,
  } = useClaimTON();

  // vTON Faucet
  const {
    claim: claimVTON,
    isPending: isVTONClaimPending,
    isConfirming: isVTONClaimConfirming,
    isConfirmed: isVTONClaimConfirmed,
    reset: resetVTONClaim,
  } = useClaimFromFaucet();
  const { claimAmount: vtonClaimAmount } = useFaucetConfig();

  // TON approval state
  const { data: tonBalance, refetch: refetchTONBalance } = useTONBalance(address);
  const { data: tonAllowance, refetch: refetchAllowance } = useTONAllowance(
    address,
    addresses.daoGovernor
  );
  const { approveAsync } = useApproveTON();

  const formattedCost = proposalCreationCost
    ? formatVTON(proposalCreationCost)
    : "100";

  const requiredAmount = proposalCreationCost ?? BigInt(100 * 10 ** 18);
  const hasEnoughTON = tonBalance >= requiredAmount;
  const hasEnoughAllowance = tonAllowance >= requiredAmount;

  // Calculate required vTON based on threshold (0.25% = 25 basis points)
  // Note: BigInt(0) is falsy in JS, so use explicit undefined checks
  const requiredVTON = (vtonTotalSupply !== undefined && proposalThreshold !== undefined)
    ? (vtonTotalSupply * proposalThreshold) / BigInt(10000)
    : BigInt(0);
  const hasEnoughVTON = totalVotingPower >= requiredVTON;

  // Refetch balances after successful claims
  React.useEffect(() => {
    if (isTONClaimConfirmed) {
      refetchTONBalance();
      const timer = setTimeout(() => resetTONClaim(), 3000);
      return () => clearTimeout(timer);
    }
  }, [isTONClaimConfirmed, refetchTONBalance, resetTONClaim]);

  React.useEffect(() => {
    if (isVTONClaimConfirmed) {
      refetchVTONBalance();
      const timer = setTimeout(() => resetVTONClaim(), 3000);
      return () => clearTimeout(timer);
    }
  }, [isVTONClaimConfirmed, refetchVTONBalance, resetVTONClaim]);

  // Register companion proposal apply handler
  React.useEffect(() => {
    registerApplyProposal((proposal: ExtractedProposal) => {
      // agenda-draft: title + RFC content + calldata
      // proposal-data (fallback): calldata.description only
      setTitle(proposal.title || proposal.calldata.description);
      setDescription(proposal.content || "");

      // Store full proposal for read-only actions display and submission
      setAgentProposal(proposal);
      setShowAdvanced(true);
    });
  }, [registerApplyProposal]);

  // Form validation
  const isFormValid =
    title.trim().length > 0 &&
    description.trim().length > 0 &&
    isConnected &&
    hasEnoughTON &&
    hasEnoughVTON;

  const [isSubmitting, setIsSubmitting] = React.useState(false);
  const [submitStep, setSubmitStep] = React.useState<"idle" | "approving" | "waitingApproval" | "proposing" | "waitingProposal">("idle");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!isFormValid || !publicClient) return;

    setIsSubmitting(true);

    try {
      // Step 1: Approve if needed
      if (!hasEnoughAllowance) {
        setSubmitStep("approving");
        const approveHash = await approveAsync(addresses.daoGovernor, requiredAmount);
        // Wait for the approval transaction to be confirmed
        setSubmitStep("waitingApproval");
        await publicClient.waitForTransactionReceipt({ hash: approveHash });
        await refetchAllowance();
      }

      // Step 2: Create proposal
      setSubmitStep("proposing");
      const fullDescription = `# ${title}\n\n${description}`;

      // Prepare action arrays — use agent calldata if available
      const agentCalldata = agentProposal?.calldata;
      const targets = agentCalldata
        ? agentCalldata.targets.map((t) => t as `0x${string}`)
        : actions.map((a) => (a.target || "0x0000000000000000000000000000000000000000") as `0x${string}`);
      const values = agentCalldata
        ? agentCalldata.targets.map(() => BigInt(0))
        : actions.map((a) => BigInt(a.value || "0"));
      const calldatas = agentCalldata
        ? agentCalldata.functionBytecodes.map((b) => b as `0x${string}`)
        : actions.map((a) => (a.calldata || "0x") as `0x${string}`);

      setSubmitStep("waitingProposal");
      // Convert percentage to basis points (e.g., 30% -> 3000)
      const burnRate = burnRateInput === "" ? 0 : Number(burnRateInput);
      const burnRateBasisPoints = Math.round(burnRate * 100);
      const proposalHash = await proposeAsync(targets, values, calldatas, fullDescription, burnRateBasisPoints);
      const receipt = await publicClient.waitForTransactionReceipt({ hash: proposalHash });

      // Parse ProposalCreated event to get the proposal ID
      const logs = parseEventLogs({
        abi: DAO_GOVERNOR_ABI,
        logs: receipt.logs,
        eventName: "ProposalCreated",
      });

      if (logs.length > 0 && logs[0].args.proposalId) {
        const proposalId = logs[0].args.proposalId.toString();
        router.push(`/proposals/${proposalId}`);
      } else {
        router.push("/proposals");
      }
    } catch (error) {
      console.error("Failed to create proposal:", error);
    } finally {
      setIsSubmitting(false);
      setSubmitStep("idle");
    }
  };

  return (
    <form onSubmit={handleSubmit} className={cn("space-y-6", className)}>
      {/* Requirements - Compact Inline Status */}
      <div className="rounded-xl border border-[var(--card-border)] bg-[var(--card-bg)] px-4 py-3">
        {!isConnected ? (
          <div className="flex items-center gap-2 text-sm text-[var(--status-warning-text)]">
            <svg className="size-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            Please connect your wallet to create a proposal.
          </div>
        ) : (
          <div className="flex flex-wrap items-center gap-x-6 gap-y-2">
            <span className="text-xs font-medium text-[var(--text-tertiary)] uppercase tracking-wider">Requirements</span>

            {/* TON Fee Status */}
            <div className="flex items-center gap-2">
              {hasEnoughTON ? (
                <svg className="size-4 text-[var(--fg-success-primary)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              ) : (
                <svg className="size-4 text-[var(--fg-error-primary)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              )}
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span className={cn(
                      "text-sm",
                      hasEnoughTON ? "text-[var(--text-secondary)]" : "text-[var(--fg-error-primary)]"
                    )}>
                      Proposal Fee ({formattedCost} TON)
                    </span>
                  </TooltipTrigger>
                  <TooltipContent>
                    Your balance: {formatVTON(tonBalance)} TON — {formattedCost} TON will be burned to prevent spam
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
              {!hasEnoughTON && (
                isTONClaimConfirmed ? (
                  <span className="text-xs text-[var(--fg-success-primary)]">Claimed!</span>
                ) : (
                  <Button
                    variant="secondary"
                    size="xs"
                    onClick={() => claimTON()}
                    loading={isTONClaimPending || isTONClaimConfirming}
                  >
                    {isTONClaimPending || isTONClaimConfirming ? "Claiming..." : `Get ${formatVTON(tonClaimAmount)} TON`}
                  </Button>
                )
              )}
            </div>

            {/* vTON Voting Power Status */}
            <div className="flex items-center gap-2">
              {isVTONDataLoading ? (
                <svg className="size-4 text-[var(--text-tertiary)] animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
              ) : hasEnoughVTON ? (
                <svg className="size-4 text-[var(--fg-success-primary)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              ) : (
                <svg className="size-4 text-[var(--fg-error-primary)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              )}
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span className={cn(
                      "text-sm",
                      isVTONDataLoading
                        ? "text-[var(--text-tertiary)]"
                        : hasEnoughVTON
                          ? "text-[var(--text-secondary)]"
                          : "text-[var(--fg-error-primary)]"
                    )}>
                      Voting Power ({isVTONDataLoading ? "..." : `${formatVTON(requiredVTON)} vTON`})
                    </span>
                  </TooltipTrigger>
                  <TooltipContent>
                    Your power: {formatVTON(totalVotingPower)} vTON (Balance: {formatVTON(vtonBalance ?? BigInt(0))} + Delegated: {formatVTON(delegatedToMe ?? BigInt(0))})
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
              {!isVTONDataLoading && !hasEnoughVTON && (
                isVTONClaimConfirmed ? (
                  <span className="text-xs text-[var(--fg-success-primary)]">Claimed!</span>
                ) : (
                  <Button
                    variant="secondary"
                    size="xs"
                    onClick={() => claimVTON()}
                    loading={isVTONClaimPending || isVTONClaimConfirming}
                  >
                    {isVTONClaimPending || isVTONClaimConfirming ? "Claiming..." : `Get ${formatVTON(vtonClaimAmount)} vTON`}
                  </Button>
                )
              )}
            </div>
          </div>
        )}
      </div>

      {/* Proposal Details */}
      <Card>
        <CardHeader>
          <CardTitle>Proposal Details</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Title */}
          <div className="space-y-2">
            <Label htmlFor="title" required>
              Title
            </Label>
            <Input
              id="title"
              placeholder="TIP-XXX: Short, descriptive title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              error={title.length > 0 && title.length < 10}
            />
            <HelperText error={title.length > 0 && title.length < 10}>
              {title.length > 0 && title.length < 10
                ? "Title should be at least 10 characters"
                : "Use a clear, concise title that describes the proposal"}
            </HelperText>
          </div>

          {/* Description */}
          <div className="space-y-2">
            <Label htmlFor="description" required>
              Description
            </Label>
            <Textarea
              id="description"
              placeholder="Provide a detailed description of your proposal. You can use Markdown for formatting.

## Summary
Brief overview of the proposal

## Motivation
Why is this proposal needed?

## Specification
Technical details of the changes

## Risks
Potential risks and mitigations"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={12}
            />
            <HelperText>
              {"Markdown formatting is supported"}
            </HelperText>
          </div>

          {/* Vote Burn Rate */}
          <div className="space-y-2">
            <Label htmlFor="burnRate">
              Vote Burn Rate (%)
            </Label>
            <Input
              id="burnRate"
              type="number"
              min={0}
              max={100}
              step={0.1}
              value={burnRateInput}
              onChange={(e) => {
                const val = e.target.value;
                if (val === "") {
                  setBurnRateInput("");
                } else {
                  const num = Number(val);
                  if (num >= 0 && num <= 100) {
                    setBurnRateInput(num.toFixed(1));
                  }
                }
              }}
              placeholder="0.0"
            />
            <HelperText>
              When voters cast their vote, this percentage of their voting power will be permanently burned as vTON (0-100%). Default is 0%.
            </HelperText>
            {burnRateInput !== "" && Number(burnRateInput) > 0 && (
              <div className="mt-2 p-3 rounded-lg bg-[var(--status-warning-bg)] text-[var(--status-warning-text)] text-sm">
                Voters will have {Number(burnRateInput).toFixed(1)}% of their voting power burned when they vote on this proposal.
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Advanced: Actions */}
      <Card>
        <CardHeader className="cursor-pointer" onClick={() => setShowAdvanced(!showAdvanced)}>
          <div className="flex items-center justify-between">
            <CardTitle>Actions</CardTitle>
            <svg
              className={cn(
                "size-5 text-[var(--text-tertiary)] transition-transform",
                showAdvanced && "rotate-180"
              )}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M19 9l-7 7-7-7"
              />
            </svg>
          </div>
        </CardHeader>

        {showAdvanced && (
          <CardContent className="space-y-4">
            {agentProposal?.calldata ? (
              <AgentActionList
                data={agentProposal.calldata}
                onClear={() => {
                  setAgentProposal(null);
                  setActions([{ ...DEFAULT_ACTION }]);
                }}
              />
            ) : (
              <>
                <HelperText>
                  Specify the on-chain actions to execute if this proposal passes.
                  Leave empty for signaling proposals. On supported networks (Sepolia, Mainnet),
                  enter a verified contract address to auto-load its ABI and build calldata.
                </HelperText>

                <ActionBuilderList actions={actions} onChange={setActions} />
              </>
            )}
          </CardContent>
        )}
      </Card>

      {/* Submit */}
      <div className="flex items-center justify-between gap-4 pt-4">
        <Button
          type="button"
          variant="secondary"
          onClick={() => router.back()}
        >
          Cancel
        </Button>

        <Button
          type="submit"
          disabled={!isFormValid || isSubmitting}
          loading={isSubmitting}
        >
          {isSubmitting
            ? submitStep === "approving"
              ? "Approve in Wallet..."
              : submitStep === "waitingApproval"
              ? "Approving TON..."
              : submitStep === "proposing"
              ? "Confirm in Wallet..."
              : submitStep === "waitingProposal"
              ? "Creating Proposal..."
              : "Processing..."
            : "Create Proposal"}
        </Button>
      </div>
    </form>
  );
}
