-- Personal Agent Model Migration
-- Run this on Supabase before deploying the new API.

-- 1. Make agent_id auto-generated (if not already SERIAL/IDENTITY)
-- Check first: SELECT column_default FROM information_schema.columns
--              WHERE table_name = 'agents' AND column_name = 'agent_id';
-- If no default exists, run:
-- ALTER TABLE agents ALTER COLUMN agent_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Add UNIQUE constraint on (owner, chain_id) for 1-owner-1-agent
ALTER TABLE agents ADD CONSTRAINT agents_owner_chain_unique UNIQUE (owner, chain_id);
